save_path = "Your Downloads file folder"
read_path = "Your [chembl.csv] which downloaded form https://www.ebi.ac.uk/chembl/"
log_config = "./log.yml"
#Limit processor for one Target in sametime
processor_limit = 4
#Limit downloads for one Uniprot Target in sametime
downloader_limit = 8
#Use '%' repalce PDB_ID
download_url = [
    # "https://s3.rcsb.org/pub/pdb/data/structures/all/pdb/pdb%.ent.gz",
    "https://ftp.wwpdb.org/pub/pdb/data/structures/all/pdb/pdb%.ent.gz",
    # "https://s3.rcsb.org/pub/pdb/data/structures/all/mmCIF/%.cif.gz",
    "https://ftp.wwpdb.org/pub/pdb/data/structures/all/mmCIF/%.cif.gz",
]
