save_path = "../promed"
read_path = "../promed/chembl.csv"
log_path = "./output.log"
#Use '%' repalce PDB_ID
download_url = [
    "https://s3.rcsb.org/pub/pdb/data/structures/all/pdb/pdb%.ent.gz",
    "https://s3.rcsb.org/pub/pdb/data/structures/all/mmCIF/%.cif.gz",
]
